---
- name: Enable Epel
  yum: name={{ sysdig_epel }} state=present

- name: Install Kernel Devel
  yum: name=kernel-devel-{{ ansible_kernel }} state=latest

- name: Fetch Sysdig Key
  rpm_key: key={{ sysdig_repokey }} state=present

- name: Fecth Sysdig repo
  get_url: url={{ sysdig_url }} dest={{ sysdig_repo }} owner=root group=root mode=0644

- name: Install Sysdig
  yum: name={{ sysdig_package }} state=latest
