---
- name: Install python-pycurl and python-apt for Debian OS family
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
   - python-pycurl
   - python-apt
  when: ansible_os_family == 'Debian'

- name: Fetch Sysdig Key for Debian OS family
  apt_key: url={{ sysdig_repokey }} state=present
  when: ansible_os_family == 'Debian'

- name: Fecth Sysdig repo for Debian OS family
  get_url: url={{ sysdig_url_apt }} dest={{ sysdig_repo_apt }} owner=root group=root mode=0644
  when: ansible_os_family == 'Debian'

- name: Install Kernel Devel for Debian OS family
  apt: pkg=kernel-devel-{{ ansible_kernel }} update_cache=yes state=latest
  when: ansible_os_family == 'Debian'

- name: Install Sysdig for Debian OS family
  apt: pkg={{ sysdig_package }} update_cache=yes state=present
  when: ansible_os_family == 'Debian'
